# Generated by Django 3.1.4 on 2020-12-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short_urls',
            old_name='short_urls',
            new_name='short_url',
        ),
    ]
